### ISSUE TITLE
"Add me as creator" erroneously populates Affiliation field

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1269] opened 2023-06-20 13:55 UTC
![Screenshot 2023-06-20 at 9 50 43 AM](https://github.com/pulibrary/pdc_describe/assets/65608/46ecadd2-2e12-475e-ba22-77f787904d7d)

**Comment by kelynch** [comment] 2023-06-20 18:43
Duplicate of #1251 , closing

**Closed by kelynch** 2023-06-20 18:43 UTC
Labels: bug
