### ISSUE TITLE
As a Curator I should see All of My Own Works AND works in the collections I Curator

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#333] opened 2022-08-24 18:58 UTC
Currently I only see the works that I submitted to the system.  Not the works that others submitted to the collection that I curate.

This will be complete when:

- [ ] The unfinished table will contain works from the logged in user and any other work that is contain in the collection
- [ ] The completed table will contain works from the logged in user and any other work that is contain in the collection

**Comment by carolyncole** [comment] 2022-08-24 18:59
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/333?planning-poker) with ZenHub @bess @jrgriffiniii @kelynch

**Comment by kelynch** [comment] 2022-10-05 15:31
Duplicate of #289

**Closed by kelynch** 2022-10-05 15:31 UTC
