### ISSUE TITLE
Describe Form: Search Feature (Admin/Curator Dashboard)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#181] opened 2022-06-27 13:50 UTC
## Description

Admin users need a convenient search feature for their dashboards that to quickly find any records using PID, Title, Name, ARK, and potentially other queries of the record metadata. 

### Image shows an example of a search feature located on the admin/curator's dashboard, though developers may have other suggestions to how this may look or function.

![Screen Shot 2022-06-24 at 4 51 10 PM](https://user-images.githubusercontent.com/50670293/175953050-e4903f16-ef8a-4c36-8231-d7fa1c778fe1.jpeg)

## User stories

Matt, a curator, was contacted by a researcher who deposited data about two years ago. Their project is still active (ongoing) and they would like to submit a new version of their dataset. Matt needs to find the record quickly to facilitate curation and deposit for this new version of an existing deposit and record.

Matt also needed to find all records by a certain research group, because they left out one of their project colleagues from the attribution, and this needs to be fixed ASAP. Matt frequently checks that depositors had entered the correct order and that all authors were cited for a work. He is also occasionally contacted by past depositors who would like to add a contributor or other additional attribution to a work, or that may wish to modify the record metadata in some way. 

Neggin, a curator, was given the task of finding all records that contain attribution to formerly named departments on campus that were previously associated with a controversial name. These departments presently have new names, so she needs to find these records quickly to update them. 

Hannah, an administrative user, was also tasked with finding all records by a certain authorship and adding contextualizing messaging to indicate how they may be used appropriately. This was requested by the depositor in cooperation with the tribal peoples they had worked with to produce the dataset.

## Acceptance Criteria
- [ ] Admin/Curator dashboards will have a search feature
- [ ] The search will query: PID, Title, Name, ARK
- [ ] The search (if possible) will query other record level metadata

**Comment by carolyncole** [comment] 2022-09-14 18:14
duplicate of #205

**Closed by carolyncole** 2022-09-14 18:14 UTC
