### ISSUE TITLE
Document process for setting up account for a non-Princeton affiliate for PDC access

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#396] opened 2022-09-08 17:56 UTC
Some researchers who do not have a Princeton University account need to collaborate on research submissions.  For instance, this is most often something that comes from PPPL researchers collaborating on projects but outside of Princeton.  They will often have a PPPL account but not an PU one.

All users who can log into PDC Describe need a PU CAS account.  This can be achieved with [sponsored guest accounts](https://guestaccount.princeton.edu/).  Document the process for sponsoring/accepting these accounts for future users.

**Comment by bess** [comment] 2022-09-15 14:15
Closing as a duplicate of #395

**Closed by bess** 2022-09-15 14:15 UTC
