### ISSUE TITLE
"Uncaught SyntaxError: import declarations may only appear at top level of a module"

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/pdc_describe#540] opened 2022-10-21 15:01 UTC
I've just deployed v0.32.0 to staging. I logged in, and I'm trying to click on the button with my NetID, but no pulldown appears: Instead in the console I see this error:
> Uncaught SyntaxError: import declarations may only appear at top level of a module

(This is not a recipe for a reproducer... I'm not sure exactly what I did before I got here.)

The link to the bad JS is https://vpn.princeton.edu/https/pdc-describe-staging.princeton.edu/describe/vite/assets/application.4e0043f6.js

```
pan_eval((function(){
import"./jquery-ui-triggeredAutocomplete.1ed59131.js";....................
```
(following code truncated)

It seems that the asset bundler isn't handling ES Modules? I'm not sure if this code changed recently.

**Comment by hectorcorrea** [comment] 2022-10-21 15:12
@mccalluc for what is worth, the file referenced `jquery-ui-triggeredAutocomplete.js` is a bit of an outlier. This is a jQuery plug-in that we are customizing for this project (since there is no official working release).

**Comment by mccalluc** [comment] 2022-10-21 15:15
More info: The pulldown with the NetID works on initial load of `/describe/`, or `/describe/users/cm7575`... but if I'm on `/describe/` and click on "My Dashboard" or "About", I get the error in the console.

**Comment by mccalluc** [comment] 2022-10-21 16:31
I'm also seeing this on production, so it may not be a new error.

**Comment by mccalluc** [comment] 2022-10-21 19:55
This doesn't show up in the dev environment: it's related to the production asset pipeline... I also wasn't able to run production locally:
```
 Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit` (ArgumentError)
```

... and trying to precompile assets and tweak dev config didn't work either... but it probably could have.

Looking at the history: This was introduced in `application.html.erb` in 
- #222 

and moved to `application.js` in
- https://github.com/pulibrary/pdc_describe/commit/150f24af29f2c9a3b5d1d44228157031d36913c2

I'll try reverting that and deploying to stage.

**Comment by mccalluc** [comment] 2022-10-24 14:20
**Important** -- The key to reproducing this is coming to the site via a VPN proxy URL like https://vpn.princeton.edu/https/pdc-describe-prod.princeton.edu/describe/

**Comment by kelynch** [comment] 2023-01-25 16:43
Let's investigate this issue.  Do we need to take action in the code?

**Comment by jrgriffiniii** [comment] 2023-01-25 17:58
I am struggling to reproduce this error. As such, I am going to please propose that this be reviewed.

**Comment by jrgriffiniii** [comment] 2023-02-08 16:12
As I still could not reproduce this error, I am going to close this in order to proceed.

**Closed by jrgriffiniii** 2023-02-08 16:12 UTC
Labels: bug
